language: go
go:
- 1.5.1
install: make
before_install:
- rm -rf dist/matter-push-proxy
deploy:
  provider: releases
  api_key:
    secure: rVUxDwoJhMM6u73HyOliZi/mAs6vlTYK3P10a9HGj1VrCfDn7XYNRqLgCrstsZLfvx4GgmLR09K/TGDUflRktwPkLxZ4ZqnY+ErcDddAt3Rs1Um3zxNwfJHfOQqJjkru/3jcVBriYDUBBzdwh4e5RiiIo1PGt905JAwzgU7Nxaw873IAwEqPZSdGzjuXbMc7pF6W1974cpqWhyS/deBQ5RaRsaSjUYf8IQEUNkyBWZ4hflvxE2uKF4o89Lq4eLwGGl/JLZGXHyNF0NVk+vJZkO7G6ICzh6+m0CfCW7F/T7Djyr2GazAjWdMsy4xJ8O0bcipafK49lftP3rKz5/un5OilqOrsSjlYgB3mjMsKaZtwOuojCBNFMd+Fn/5i6OmINz70Ddeb5mJW+OeV6t/BoVUx6EsauR9N9dUynLnktr0Ym95vC/bIO6n1PPO4ML/EAtAZa6WWctQhgMYOg/QhnbUhoL4n9PkDSblKN1dFT2kY5Z/MQKUCZrlEpAbmZiUB0EhDGpQL1zTb5k58DWkeV5W9KfFkNxT5h32vLlMjPyyxxN7p1lyHZ+5KqpX7uOjW15Tu+D9PNCID0rzRDqt/rbwLWVcnudi7ZRdsYy+Lo0YwdN87WqwnWySB1Y4M8pLGicPJ8x9gU+8Rq226I8CIhvCD8RoVksmhhv6O7NQp3ac=
  file: dist/matter-push-proxy.tar.gz
  skip_cleanup: true
  on:
    repo: mattermost/push-proxy
